export const inventoryRoutes = [
  "/",
  "/new",
  "/assistant",
  "/matters",
  "/matters/matter-rta-001",
  "/matters/matter-rta-001/documents",
  "/matters/matter-rta-001/facts",
  "/matters/matter-rta-001/workflow",
  "/matters/matter-rta-001/checks",
  "/matters/matter-rta-001/drafts",
  "/matters/matter-rta-001/drafts/draft-form8-001",
  "/matters/matter-rta-001/activity",
  "/workflows",
  "/workflows/workflow-exam-001",
  "/history",
  "/library",
  "/settings",
  "/help",
] as const;
