steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - frontend/Dockerfile
      - --build-arg
      - NEXT_PUBLIC_API_BASE_URL=${_API_URL}
      - --build-arg
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_CLERK_PUBLISHABLE_KEY}
      - --tag
      - ${_IMAGE}
      - frontend
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
